export const navItems = [
  { label: 'Thesis', href: '#hero' },
  { label: 'Problem', href: '#problem' },
  { label: 'ROI', href: '#roi' },
  { label: 'System', href: '#system' },
  { label: 'Budget', href: '#budget' },
  { label: 'Timeline', href: '#timeline' },
  { label: 'Ask', href: '#ask' },
]

export const metrics = [
  { value: 67, suffix: '%', label: 'of B2B buyers form an opinion from your website before speaking to sales', ref: 1 },
  { value: 3, suffix: 'x', label: 'more pipeline generated by companies with a strong digital presence', ref: 2 },
  { value: 47, suffix: '%', label: 'higher close rates when prospects self-educate before first call', ref: 3 },
  { value: 2.3, suffix: 'x', label: 'faster sales cycles with modern sales enablement infrastructure', ref: 4 },
]

export const problems = [
  {
    title: 'The site does not sell',
    body: 'The current site describes services. It does not establish authority, build conviction, or move a prospect toward a decision. It is a brochure in a world that demands a sales system.',
  },
  {
    title: 'Sales has no infrastructure',
    body: 'Every proposal, deck, and leave-behind is rebuilt from scratch. There is no shared system, no consistent narrative, no tooling that compounds over time.',
  },
  {
    title: 'Brand equity is not captured',
    body: 'Lazer has deep expertise and exceptional outcomes. None of that is legible to a first-time visitor. The gap between what we deliver and what we project is a direct revenue leak.',
  },
  {
    title: 'Competitors are moving',
    body: 'Peer firms are investing heavily in digital infrastructure. The window to differentiate on experience — before it becomes table stakes — is closing.',
  },
]

export const systemPillars = [
  {
    number: '01',
    title: 'Brand & Identity System',
    items: [
      'Visual identity refresh',
      'Brand guidelines & tokens',
      'Typography & color system',
      'Iconography & illustration direction',
    ],
  },
  {
    number: '02',
    title: 'Website Rebuild',
    items: [
      'New information architecture',
      'High-performance CMS build',
      'Case study engine',
      'SEO & performance foundation',
      'Analytics instrumentation',
    ],
  },
  {
    number: '03',
    title: 'Sales Enablement System',
    items: [
      'Proposal templates',
      'Pitch deck system',
      'One-pager library',
      'Case study format',
      'RFP response kit',
    ],
  },
]

export const budgetItems = [
  { phase: 'Discovery & Strategy', description: 'Stakeholder interviews, competitive audit, positioning workshops', investment: 18000 },
  { phase: 'Brand Evolution', description: 'Identity refresh, guidelines, design system', investment: 32000 },
  { phase: 'Website Rebuild', description: 'UX, design, development, CMS, QA, launch', investment: 64000 },
  { phase: 'Sales Enablement System', description: 'Templates, decks, one-pagers, case study engine', investment: 28000 },
  { phase: 'Launch & Enablement', description: 'Training, documentation, 60-day support', investment: 8000 },
]

export const timelinePhases = [
  { phase: 'Phase 1', label: 'Discovery', duration: 'Weeks 1–3', deliverables: ['Stakeholder interviews', 'Competitive audit', 'Positioning brief', 'Project roadmap'] },
  { phase: 'Phase 2', label: 'Brand', duration: 'Weeks 4–8', deliverables: ['Identity concepts', 'Design system', 'Brand guidelines', 'Asset library'] },
  { phase: 'Phase 3', label: 'Website', duration: 'Weeks 9–18', deliverables: ['IA & wireframes', 'Visual design', 'Development', 'CMS & QA'] },
  { phase: 'Phase 4', label: 'Sales System', duration: 'Weeks 14–20', deliverables: ['Proposal templates', 'Pitch deck', 'One-pager library', 'Case study format'] },
  { phase: 'Phase 5', label: 'Launch', duration: 'Weeks 21–22', deliverables: ['Soft launch', 'Redirects & SEO', 'Team training', 'Handoff docs'] },
]

export const references = [
  { id: 1, citation: 'Demand Gen Report, B2B Buyer Behavior Study, 2023. "67% of the buyer\'s journey is now done digitally before engaging a sales rep."' },
  { id: 2, citation: 'Forrester Research, "The Business Impact of Digital Experience," 2023. Companies with superior digital presence generate 3x more qualified pipeline.' },
  { id: 3, citation: 'HubSpot State of Inbound Sales Report, 2024. Self-educated buyers close 47% more often and require fewer touchpoints.' },
  { id: 4, citation: 'Gartner, Sales Enablement Technology Market Guide, 2024. Organizations with mature sales enablement achieve 2.3x faster deal cycles.' },
  { id: 5, citation: 'McKinsey & Company, "The B2B digital inflection point," 2024. Digital-first B2B companies grow revenue 5x faster than peers.' },
  { id: 6, citation: 'Nielsen Norman Group, Website UX & Credibility Study, 2023. First impressions form in 50ms; 75% of credibility judgments are design-based.' },
]

export const totalBudget = 150000
export const paybackMonths = 8
